name: Build and Push Docker Image

on:
  push:
    # branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image from main branch
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.jenkins-agent
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/starbuggx/jenkins-agent-utility:latest

      - name: Build and push Docker image from other branches
        if: github.ref_name != 'main'
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.jenkins-agent
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/starbuggx/jenkins-agent-utility:${{ github.ref_name }}
          
